In [1]:
import numpy as np

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0.5,2,0.01,8]
a2 = np.array(data2)
a2

array([0.5 , 2.  , 0.01, 8.  ])

In [5]:
a1.dtype

dtype('int32')

In [9]:
a2.dtype

dtype('float64')

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b1 = np.arange(6).reshape(2,3)
b1.shape

(2, 3)

In [11]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
np.linspace(0, np.pi, 10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.array(['1.3','2','0.14','3.141592'])

array(['1.3', '2', '0.14', '3.141592'], dtype='<U8')

In [25]:
str_arr = np.array(['1.3','2','0.14','3.141592'])
num_arr = str_arr.astype(float)
num_arr

array([1.3     , 2.      , 0.14    , 3.141592])

In [20]:
float_arr=np.array([10,22,0.315, 3.14, 6.8])
float_arr.astype(int)

array([10, 22,  0,  3,  6])

In [34]:
str_arr.dtype

dtype('<U8')

In [35]:
num_arr.dtype

dtype('float64')

In [26]:
float_arr = np.array([10, 22, 0.315, 3.14, 6.8])
int_arr = float_arr.astype(int)

In [27]:
int_arr

array([10, 22,  0,  3,  6])

In [28]:
np.random.rand()

0.6204293045719067

In [29]:
np.random.rand(2,3)

array([[0.67957996, 0.1705593 , 0.66145813],
       [0.77721911, 0.93953569, 0.66242106]])

In [30]:
np.random.rand(2,3,2)

array([[[0.65029398, 0.98778013],
        [0.10895768, 0.00148204],
        [0.37521846, 0.06152684]],

       [[0.00768375, 0.35224199],
        [0.53269957, 0.16766882],
        [0.30753129, 0.46937949]]])

In [41]:
np.random.rand(2,3,2,3)

array([[[[0.46330398, 0.1951693 , 0.00818473],
         [0.67769402, 0.6913193 , 0.57816406]],

        [[0.22047295, 0.06272297, 0.25940758],
         [0.64200184, 0.35425373, 0.74055244]],

        [[0.80855117, 0.87343936, 0.99168764],
         [0.67551941, 0.24244334, 0.92345286]]],


       [[[0.8817049 , 0.35356636, 0.48569734],
         [0.23224601, 0.14794045, 0.20514254]],

        [[0.2292831 , 0.95541926, 0.44738142],
         [0.93195749, 0.27034885, 0.11616511]],

        [[0.73805851, 0.49261069, 0.54463866],
         [0.8415223 , 0.6614379 , 0.87928623]]]])

In [31]:
np.random.randint(10, size=(2,3))

array([[9, 8, 7],
       [1, 8, 5]])

In [32]:
np.random.randint(1, 20)

9

In [33]:
num_arr1 = np.array([10, 20, 30])
num_arr2 = np.array([1,2,3])

In [34]:
num_arr1 + num_arr2

array([11, 22, 33])

In [48]:
num_arr1 - num_arr2

array([ 9, 18, 27])

In [49]:
num_arr1 * 2

array([20, 40, 60])

In [50]:
num_arr1 ** 2

array([100, 400, 900], dtype=int32)

In [51]:
num_arr1 * num_arr2

array([10, 40, 90])

In [52]:
num_arr1 / num_arr2

array([10., 10., 10.])

In [53]:
num_arr1 / (num_arr2 ** 2)

array([10.        ,  5.        ,  3.33333333])

In [54]:
num_arr1 > 20

array([False, False,  True])

In [35]:
num_arr = np.arange(1,6)
num_arr

array([1, 2, 3, 4, 5])

In [36]:
[num_arr.sum(), num_arr.mean()] #합과 평균

[15, 3.0]

In [37]:
[num_arr.std(), num_arr.var()] #표준편차와 분산

[1.4142135623730951, 2.0]

In [38]:
[num_arr.min(), num_arr.max()] #최소값과 최대값

[1, 5]

In [39]:
[num_arr.cumsum(), num_arr.cumprod()] #누적합과 누적곱

[array([ 1,  3,  6, 10, 15], dtype=int32),
 array([  1,   2,   6,  24, 120], dtype=int32)]

In [41]:
m1 = np.array([0,1,2,3]).reshape(2,2)
m1

array([[0, 1],
       [2, 3]])

In [42]:
m2 = np.array([3,2,1,0]).reshape(2,2)
m2

array([[3, 2],
       [1, 0]])

In [43]:
m1.dot(m2) # 행렬곱

array([[1, 0],
       [9, 4]])

In [44]:
np.dot(m1, m2) # 행렬곱2

array([[1, 0],
       [9, 4]])

In [45]:
m1.transpose() # 전치행렬

array([[0, 2],
       [1, 3]])

In [46]:
np.transpose(m1) # 전치행렬2

array([[0, 2],
       [1, 3]])

In [47]:
np.linalg.inv(m1) # 역행렬

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [48]:
np.linalg.det(m1) # 행렬식

-2.0

In [74]:
num_arr = np.array([10,20,30,40,50])

In [75]:
num_arr[0]

10

In [77]:
num_arr[4]

50

In [50]:
arr_m = np.arange(10, 100, 10).reshape(3,3)
arr_m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
arr_m[0,2]

30

In [52]:
arr_m[2,2]=95
arr_m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [85]:
arr_m[1]

array([40, 50, 60])

In [53]:
arr_m[1] = np.array([45,55,65])
arr_m

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [54]:
arr_m[1] = [47,57,67]
arr_m

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [55]:
arr_m[[0,2],[0,1]]

array([10, 80])

In [56]:
a = np.array([10,20,30,40,50])
a[a>25]

array([30, 40, 50])

In [91]:
a[(a%2)==0]

array([10, 20, 30, 40, 50])

In [92]:
arr_m

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [57]:
arr_m = np.arange(10, 100, 10).reshape(3,3)
arr_m

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
arr_m[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [59]:
arr_m[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [60]:
arr_m[1][0:2]

array([40, 50])

In [98]:
arr_m[0:2, 1:3] = np.array([[25,35],[55,65]])
arr_m

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [100]:
arr_m[0:2, 1:3]

array([[25, 35],
       [55, 65]])